# This file is used to configure your project.
# Read more about the various options under:
# https://setuptools.pypa.io/en/latest/userguide/declarative_config.html
# https://setuptools.pypa.io/en/latest/references/keywords.html

[metadata]
name = impacts
description = Convert transportation emissions outputs into gridded air-quality and exposure artifacts.
author = Haitam Laarabi
author_email = 10712736+htmlrb@users.noreply.github.com
license = MIT
license_files = LICENSE.txt
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8
url = https://github.com/LBNL-UCB-STI/IMPACTS
project_urls =
    Source = https://github.com/LBNL-UCB-STI/IMPACTS
    Issues = https://github.com/LBNL-UCB-STI/IMPACTS/issues

platforms = any

classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Science/Research
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Topic :: Scientific/Engineering


[options]
zip_safe = False
packages = find_namespace:
include_package_data = True
package_dir =
    =src
python_requires = >=3.10
install_requires =
    osm-chordify>=0.2.2
    geopandas>=0.11.1
    duckdb>=1.1.0
    pyarrow>=14
    scipy>=1.10
    zarr==3.1.5
    s3fs
    matplotlib>=3.9.0


[options.packages.find]
where = src
exclude =
    tests

[options.extras_require]
testing =
    setuptools
    pytest
    pytest-cov

[options.entry_points]

[tool:pytest]
addopts =
    --cov impacts --cov-report term-missing
    --verbose
norecursedirs =
    dist
    build
    .tox
testpaths = tests

[flake8]
max_line_length = 88
extend_ignore = E203, W503
exclude =
    .tox
    build
    dist
    .eggs
    docs/conf.py
