fleet:
  region: sfbay
  scenario: 2018-Baseline
  output: ~/Workspace/Simulation/sfbay/vehicle-tech

  emfac:
    rates_file: ~/Workspace/Models/emfac/processed/2018/sf-emfac-2018-project-analysis-final-rates.parquet
    activity_file: ~/Workspace/Models/emfac/processed/2018/sf-emfac-2018-project-analysis-final-activity.parquet
    atlas_emfac_xwalk: ~/Workspace/Simulation/sfbay/atlas/atlas-emfac-xwalk.csv

  atlas:
    vehicles_file: data/fleet/sfbay-atlas-base-20240711/year-2029-iteration-2/vehicles.parquet
    vehicles_types_file: data/fleet/sfbay-atlas-base-20240711/year-2029-iteration-2/vehicleTypes_inventory.csv
    curb_weight_mapping_file: data/fleet/sfbay-atlas-base-20240711/year-2029-iteration-2/vehicleType_curbWeight_mapping.csv

  beam:
    beam_household_vehicles_file: data/fleet/vehicles.csv.gz
    freight_directory: ~/Workspace/Simulation/sfbay/beam-ft/20250730/2018-Baseline
    ft_vehicle_types_file: ~/Workspace/Simulation/sfbay/vehicle-tech/vehicletypes--frism--2018-Baseline.csv
    pax_vehicles_file: ~/Workspace/Simulation/sfbay/atlas/vehicles_2017.csv
    pax_vehicle_types_file: ~/Workspace/Simulation/sfbay/vehicle-tech/vehicleTypes--atlas--2017-Baseline.csv
