emfac:
  region:
    name: sfbay
    label: SF
  scenario:
    year: 2018
    name: Baseline
  seed: 0
  output: /global/scratch/users/hmlaarabi/sources/PILATES/pilates/beam/production/sfbay/vehicle-tech

  activities:
    model_year_groups:
      light_duty:
        - "<=2003"
        - "2004-2014"
        - ">=2015"
      medium_heavy_duty:
        - "<=2002"
        - "2003-2006"
        - "2007-2009"
        - "2010-2012"
        - "2013-2015"
        - ">=2016"
    project_analysis:
      - main:
          - folder: /global/scratch/users/hmlaarabi/sources/PILATES/pilates/beam/production/sfbay/vehicle-tech/emissions/sfbay-emfac-project-analysis
          - pto_as_process:
              enabled: true
              vehicle_category:
                - T7 Public Class 8
                - T7 Utility Class 8
                - T7 Single Concrete/Transit Mix Class 8
                - T7 Single Dump Class 8
                - T7 Single Other Class 8
                - T7 SWCV Class 8
      - black_carbon:
          - folder: /global/scratch/users/hmlaarabi/sources/PILATES/pilates/beam/production/sfbay/vehicle-tech/emissions/sfbay-emfac-moves-bc
          - pollutant: BCh
      - paved_road_dust:
          - folder: /global/scratch/users/hmlaarabi/sources/PILATES/pilates/beam/production/sfbay/vehicle-tech/emissions/statewide-carb-road-dust
          - road_category_map:
              motorway: Freeway
              motorway_link: Freeway
              trunk: Freeway
              trunk_link: Major
              primary: Major
              primary_link: Major
              secondary: Collector
              secondary_link: Collector
              tertiary: Collector
              tertiary_link: Collector
              unclassified: Collector
              residential: Local Urban
              residential_link: Local Urban
    emissions_inventory:
      - inventory_folder: /global/scratch/users/hmlaarabi/sources/PILATES/pilates/beam/production/sfbay/vehicle-tech/emissions/sfbay-emfac-emissions-inventory
      - fallback_folder: /global/scratch/users/hmlaarabi/sources/PILATES/pilates/beam/production/sfbay/vehicle-tech/emissions/statewide-emfac-emissions-inventory
      - vehicle_category_attributes_file: /global/scratch/users/hmlaarabi/sources/PILATES/pilates/beam/production/sfbay/vehicle-tech/emissions/emfac_vehicle_category_attributes.csv
      - fuel_map:
          Dsl: [Diesel]
          Elec: [Electricity]
          Gas: [Gasoline]
          NG: [Natural Gas]
          Phe: [Plug-in Hybrid]
