main:
  mapping_section: osm_grid
  rates_section: emissions_rates
  dispersion_section: dispersion_isrm

osm_grid:
  osm_links_path: null
  grid_cells_path: data/input/grid_polygon/grid_polygon.shp
  beam_network_path: null
  precomputed_beam_osm_path: null
  output_dir: src/impacts/tmp
  beam_osm_id_col: attributeOrigId
  beam_length_col: linkLength
  beam_osm_epsg: 4326
  grid_epsg: 4326
  output_epsg: 26910

emissions_rates:
  rates_dir: null
  default_rate_basis: per_event

dispersion_isrm:
  isrm_url: s3://inmap-model/isrm_v1.2.1.zarr/
  emissions_input_path: null
  concentration_output_path: src/impacts/tmp/grid_concentration.parquet
  concentration_factor: 28766.639
  include_bc: false
  include_health: false
