fleet:
  region: sfbay
  scenario: 2018-Baseline
  output: vehicle-tech/emissions/2018-Baseline

  emfac:
    rates_file: ~/Workspace/Models/emfac/processed/2018/sf-emfac-2018-project-analysis-final-rates.parquet
    activity_file: ~/Workspace/Models/emfac/processed/2018/sf-emfac-2018-project-analysis-final-activity.parquet

  beam:
    freight_directory: ~/Workspace/Simulation/sfbay/beam-ft/20250730/2018-Baseline
    ft_vehicle_types_file: vehicle-tech/vehicleTypes--frism--2018-Baseline.csv
    pax_vehicles_file: beam-pax/vehicles--atlas--2017-Baseline.csv.gz
    pax_vehicle_types_file: vehicle-tech/vehicleTypes--atlas--2017-Baseline.csv
