run:
  models:
    impacts: impacts

impacts:
  runtime_overrides:
    emissions:
      annualization_days: 330
      activity_correction_factors_file:
      pollutants:
        - NH3
        - NOx
        - PM2_5
        - SOx
        - ROG
        - BCh
    dispersions:
      inmap:
        isrm_zarr_directory:
        isrm_zarr_s3bucket: s3://inmap-model/isrm_v1.2.1.zarr/
        grid_path:
        grid_epsg:
        grid_id:
      aermod:
        grid_path:
        grid_epsg:
        grid_id:
    outputs:
      output_dir: ./impacts/output
