run:
  region: sfbay
  scenario: base
  start_year: 2017

shared:
  geography:
    FIPS:
      state: "06"
      counties:
        - "001"
        - "013"
        - "041"
        - "055"
        - "075"
        - "081"
        - "085"
        - "095"
        - "097"
    local_crs: EPSG:26910


beam:
  local_input_folder: pilates/beam/production/
  local_output_folder: beam/beam_output/

impacts:
  override_files: false
  local_input_folder: impacts/input/
  local_output_folder: impacts/impacts_output/
  emissions:
    osm_network_folder: r5/sfbay-cbg5500-weakConn-network
    emissions_rates_folder: vehicle-tech/emissions/2018-Baseline
    activity_totals_file: vehicle-tech/emissions/SFBay_2018_Annual_activity_totals.parquet
    annualization_days: 330
    population_sample: 0.1
    pollutants_map:
      NH3: NH3
      NOx: NOx
      PM2_5: PM2_5
      SOx: SOx
      ROG: ROG
      BC: BCh
  dispersions:
    inmap:
      enabled: true
      isrm_zarr: ~/Workspace/Simulation/sfbay/inmap/isrm_v1.2.1.zarr
      isrm_nox_to_no2_matrix_npz: vehicle-tech/dispersions/inmap/nox_to_no2_full_isrm_matrix.npz
      isrm_nox_to_no2_matrix_factor: 1.0
      grid_path: vehicle-tech/dispersions/inmap/isrm_polygon_wgs84.gpkg
      grid_id: isrm
      grid_epsg: 4326
    aermod:
      enabled: true
      grid_size_meters: 100.0
      asrv_patterns_file: vehicle-tech/dispersions/aermod/aermod_patterns_wgs84.parquet
      asrv_patterns_epsg: 4326
  exposure:
    enabled: true
    population_folder: urbansim/2018

