run:
  region: sfbay
  scenario: base
  start_year: 2017

shared:
  geography:
    FIPS:
      state: "06"
      counties:
        - "001"
        - "013"
        - "041"
        - "055"
        - "075"
        - "081"
        - "085"
        - "095"
        - "097"
    local_crs: EPSG:26910

impacts:
  local_input_folder: upstream/
  local_output_folder: downstream/
  emissions:
    simulation_network_folder: upstream/
    osm_network_folder: upstream/
    emissions_rates_folder: upstream/
    activity_corrections: upstream/activity_corrections.csv
    annualization_days: 330
    pollutants:
      - NH3
      - NOx
      - PM2_5
      - SOx
      - ROG
      - BC
    pollutants_map:
      BC: BCh
  dispersions:
    inmap:
      isrm_zarr: ~/Workspace/Simulation/sfbay/inmap/isrm_v1.2.1.zarr
      isrm_nox_to_no2_matrix_npz: {local_input_folder}/nox_to_no2_full_isrm_matrix.npz
      grid_path: {local_input_folder}/isrm_polygon/isrm_polygon.shp
      grid_id: isrm
      grid_epsg:
    aermod:
      grid_path:
      grid_epsg:
      grid_id:
